FROM slack-attendance-bot:latest
USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin

RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata xvfb fluxbox x11vnc novnc websockify \
 && rm -rf /var/lib/apt/lists/*

COPY entrypoint.vnc.sh /usr/local/bin/entrypoint.vnc.sh
RUN chmod +x /usr/local/bin/entrypoint.vnc.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.vnc.sh"]
